service: task-kinesis

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - firehose:PutRecord
      Resource: "arn:aws:firehose:us-east-1:657750297473:deliverystream/PUT-S3-EBGEB"

functions:
  sendToFirehose:
    handler: handler.sendToFirehose
    events:
      - http:
          path: sendToFirehose
          method: post # Example event trigger, can be replaced with your own trigger
      - firehose:
        arn: "arn:aws:firehose:us-east-1:657750297473:deliverystream/PUT-S3-EBGEB"